
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cylydrighzzovpnnubwm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN5bHlkcmlnaHp6b3Zwbm51YndtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwMzQzOTksImV4cCI6MjA1OTYxMDM5OX0.aOF1jj_E6YkAjX8_NpOupjgVF8oR2rdpcvS_bE4gEO0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      autoRefreshToken: true,
      persistSession: true,
    }
  }
);
